!*******************************************************************************
!$RCSfile$
!$Revision$
!$Date$
!*******************************************************************************
MODULE write_fd

  USE contour_fd

  INTEGER, PARAMETER ::  BFILE_APPEND   = 15
  INTEGER, PARAMETER ::  FILE_APPEND    =  2**BFILE_APPEND
  INTEGER, PARAMETER ::  BFILE_FOOTER   = 14
  INTEGER, PARAMETER ::  FILE_FOOTER    =  2**BFILE_FOOTER
  INTEGER, PARAMETER ::  BFILE_HEADER   = 13
  INTEGER, PARAMETER ::  FILE_HEADER    =  2**BFILE_HEADER
  INTEGER, PARAMETER ::  BWRITE_CONTOUR = 10
  INTEGER, PARAMETER ::  WRITE_CONTOUR  =  2**BWRITE_CONTOUR

  INTEGER, PARAMETER ::  BAVS_FORMAT    =  0
  INTEGER, PARAMETER ::   AVS_FORMAT    =  2**BAVS_FORMAT
  INTEGER, PARAMETER ::   AVS_FILE      =  AVS_FORMAT + FILE_HEADER

  INTEGER, PARAMETER ::  BOVL_FORMAT    =  1
  INTEGER, PARAMETER ::   OVL_FORMAT    =  2**BOVL_FORMAT
  INTEGER, PARAMETER ::   OVL_FILE      =  OVL_FORMAT + WRITE_CONTOUR + FILE_HEADER
  INTEGER, PARAMETER ::   ARC_FILE      =  OVL_FILE   + LATLON_OUTPUT + CLOSE_CONTOUR
  INTEGER, PARAMETER ::   CMP_FILE      =  ARC_FILE

  INTEGER, PARAMETER ::  BCTS_FORMAT    =  2
  INTEGER, PARAMETER ::   CTS_FORMAT    =  2**BCTS_FORMAT
  INTEGER, PARAMETER ::   CTS_FILE      =  CTS_FORMAT + LATLON_OUTPUT + WRITE_CONTOUR + FILE_HEADER + FILE_FOOTER

  INTEGER, PARAMETER ::  BEIS_FORMAT    =  3
  INTEGER, PARAMETER ::   EIS_FORMAT    =  2**BEIS_FORMAT
  INTEGER, PARAMETER ::   EIS_FILE      =  EIS_FORMAT + LATLON_OUTPUT + CLOSE_CONTOUR + WRITE_CONTOUR + FILE_HEADER + FILE_FOOTER

  INTEGER, PARAMETER ::  BOIL_FORMAT    =  4
  INTEGER, PARAMETER ::   OIL_FORMAT    =  2**BOIL_FORMAT
  INTEGER, PARAMETER ::   OIL_FILE      =  OIL_FORMAT + LATLON_OUTPUT + CLOSE_CONTOUR + WRITE_CONTOUR + FILE_HEADER

  INTEGER, PARAMETER ::  BUSA_FORMAT    =  5
  INTEGER, PARAMETER ::   USA_FORMAT    =  2**BUSA_FORMAT
  INTEGER, PARAMETER ::   USA_FILE      =  USA_FORMAT + LATLON_OUTPUT + WRITE_CONTOUR

  INTEGER, PARAMETER ::   BNO_FORMAT    =  6
  INTEGER, PARAMETER ::    NO_FORMAT    =  2**BNO_FORMAT
  INTEGER, PARAMETER ::    NO_FILE      =  NO_FORMAT

  INTEGER, PARAMETER ::BCOUNT_FORMAT    =  7
  INTEGER, PARAMETER :: COUNT_FORMAT    =  2**BCOUNT_FORMAT
  INTEGER, PARAMETER :: COUNT_FILE      =  COUNT_FORMAT

END MODULE write_fd
