!*******************************************************************************
!$RCSfile$
!$Revision$
!$Date$
!*******************************************************************************
MODULE statstruct_fd
  USE list_fd         !Basic list structures
  USE prjstruct_fd    !Basic project structures

  INTEGER,PARAMETER :: HS_READSCN    = -3
  INTEGER,PARAMETER :: HS_READTIME   = -2
  INTEGER,PARAMETER :: HS_READDOMAIN = -1
  INTEGER,PARAMETER :: HS_READALL    =  0

  INTEGER,PARAMETER :: HS_MAXTIMESTATUS = 5
  INTEGER,PARAMETER :: HSI_TIMESTATUS   = 1
  INTEGER,PARAMETER :: HSI_TIMESTART    = 2
  INTEGER,PARAMETER :: HSI_TIMEEND      = 3
  INTEGER,PARAMETER :: HSI_TIMELOCAL    = 4
  INTEGER,PARAMETER :: HSI_TIMEZONE     = 5

  INTEGER,PARAMETER :: HS_MAXDOMAINSTATUS = 20
  INTEGER,PARAMETER :: HSI_DOMAINSTATUS  =  1
  INTEGER,PARAMETER :: HSI_DOMAINXMIN    =  2
  INTEGER,PARAMETER :: HSI_DOMAINXMAX    =  3
  INTEGER,PARAMETER :: HSI_DOMAINYMIN    =  4
  INTEGER,PARAMETER :: HSI_DOMAINYMAX    =  5
  INTEGER,PARAMETER :: HSI_DOMAINZMIN    =  6
  INTEGER,PARAMETER :: HSI_DOMAINZMAX    =  7
  INTEGER,PARAMETER :: HSI_DOMAINTYPE    =  8
  INTEGER,PARAMETER :: HSI_DOMAINREF     =  9
  INTEGER,PARAMETER :: HSI_DOMAINREFLON  = 10
  INTEGER,PARAMETER :: HSI_DOMAINREFLAT  = 11
  INTEGER,PARAMETER :: HSI_DOMAINREFALT  = 12
  INTEGER,PARAMETER :: HSI_DOMAINREFX    = 13
  INTEGER,PARAMETER :: HSI_DOMAINREFY    = 14
  INTEGER,PARAMETER :: HSI_DOMAINREFZ    = 15
  INTEGER,PARAMETER :: HSI_DOMAINREFUTM  = 16
  INTEGER,PARAMETER :: HSI_DOMAINVRES    = 20

  INTEGER, PARAMETER :: HS_MAXRELSTATUS = 11
  INTEGER, PARAMETER :: HSI_RELSTATUS   =  1
  INTEGER, PARAMETER :: HSI_RELTIME     =  2
  INTEGER, PARAMETER :: HSI_RELX        =  3
  INTEGER, PARAMETER :: HSI_RELY        =  4
  INTEGER, PARAMETER :: HSI_RELZ        =  5
  INTEGER, PARAMETER :: HSI_RELHUNC     =  6
  INTEGER, PARAMETER :: HSI_RELVUNC     =  7
  INTEGER, PARAMETER :: HSI_RELMTL      =  8
  INTEGER, PARAMETER :: HSI_RELFILE     =  9
  INTEGER, PARAMETER :: HSI_RELPATH     = 10
  INTEGER, PARAMETER :: HSI_RELUTM      = 11

  INTEGER, PARAMETER :: HSI_RELCONTDISTR =  1
  INTEGER, PARAMETER :: HSI_RELCONTRATE  =  2
  INTEGER, PARAMETER :: HSI_RELCONTDUR   =  3
  INTEGER, PARAMETER :: HSI_RELCONTSIGY  =  4
  INTEGER, PARAMETER :: HSI_RELCONTSIGZ  =  5
  INTEGER, PARAMETER :: HSI_RELCONTMMD   =  6
  INTEGER, PARAMETER :: HSI_RELCONTSIG   =  7
  INTEGER, PARAMETER :: HSI_RELCONTMOM   =  8
  INTEGER, PARAMETER :: HSI_RELCONTBUOY  =  9

  INTEGER, PARAMETER :: HSI_RELFILERAND   =  1
  INTEGER, PARAMETER :: HSI_RELFILESEED   =  2
  INTEGER, PARAMETER :: HSI_RELFILESPREAD =  3
  INTEGER, PARAMETER :: HSI_RELINSTDISTR  =  1
  INTEGER, PARAMETER :: HSI_RELINSTMASS   =  2
  INTEGER, PARAMETER :: HSI_RELINSTSIGX   =  3
  INTEGER, PARAMETER :: HSI_RELINSTSIGY   =  4
  INTEGER, PARAMETER :: HSI_RELINSTSIGZ   =  5
  INTEGER, PARAMETER :: HSI_RELINSTMMD    =  6
  INTEGER, PARAMETER :: HSI_RELINSTSIG    =  7
  INTEGER, PARAMETER :: HSI_RELINSTMOM    =  8
  INTEGER, PARAMETER :: HSI_RELINSTBUOY   =  9
  INTEGER, PARAMETER :: HSI_RELINSTRAND   = 10
  INTEGER, PARAMETER :: HSI_RELINSTSEED   = 11
  INTEGER, PARAMETER :: HSI_RELINSTSPREAD = 12

  INTEGER, PARAMETER :: HSI_RELMOVEDISTR  =  1
  INTEGER, PARAMETER :: HSI_RELMOVERATE   =  2
  INTEGER, PARAMETER :: HSI_RELMOVEDUR    =  3
  INTEGER, PARAMETER :: HSI_RELMOVESIGY   =  4
  INTEGER, PARAMETER :: HSI_RELMOVESIGZ   =  5
  INTEGER, PARAMETER :: HSI_RELMOVEMMD    =  6
  INTEGER, PARAMETER :: HSI_RELMOVESIG    =  7
  INTEGER, PARAMETER :: HSI_RELMOVEMOM    =  8
  INTEGER, PARAMETER :: HSI_RELMOVEBUOY   =  9
  INTEGER, PARAMETER :: HSI_RELMOVEVELX   = 10
  INTEGER, PARAMETER :: HSI_RELMOVEVELY   = 11
  INTEGER, PARAMETER :: HSI_RELMOVEVELZ   = 12

  INTEGER, PARAMETER :: HSI_RELPOOLMASS  =  1
  INTEGER, PARAMETER :: HSI_RELPOOLSIZEX =  2
  INTEGER, PARAMETER :: HSI_RELPOOLSIZEY =  3

  INTEGER, PARAMETER :: HSI_RELSTKDISTR =  1
  INTEGER, PARAMETER :: HSI_RELSTKRATE  =  2
  INTEGER, PARAMETER :: HSI_RELSTKDUR   =  3
  INTEGER, PARAMETER :: HSI_RELSTKDIAM  =  4
  INTEGER, PARAMETER :: HSI_RELSTKMMD   =  5
  INTEGER, PARAMETER :: HSI_RELSTKSIG   =  6
  INTEGER, PARAMETER :: HSI_RELSTKVEL   =  7
  INTEGER, PARAMETER :: HSI_RELSTKTEMP  =  8

!==== pstatusT

  TYPE  pstatusT
    SEQUENCE
    TYPE( projectIDT  ) project
    INTEGER             ID
    TYPE( listHeadT   ) statHead
  END TYPE  pstatusT

  INTEGER, PARAMETER :: SIZE_pstatusT = SIZE_projectIDT + KIND(1) + SIZE_listHeadT

END MODULE statstruct_fd
